/* dircproxy
 * Copyright (C) 2000 Scott James Remnant <scott@netsplit.com>.
 * All Rights Reserved.
 *
 * dns.c
 *  - non-blocking DNS lookups using callbacks
 *  - wrappers around /etc/services lookup functions
 *
 * The non-blocking stuff is a little complex, but it means that the main
 * loop can continue while waiting for DNS requests to complete.  Completion
 * of a DNS request is notified by the child death signal, so it will
 * interrupt the main loop to continue where you left off.
 * --
 * @(#) $Id: dns.c,v 1.7 2000/10/13 12:32:46 keybuk Exp $
 *
 * This file is distributed according to the GNU General Public
 * License.  For full details, read the top of 'main.c' or the
 * file called COPYING that was distributed with this code.
 */

#include <sys/param.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <netdb.h>

#include <dircproxy.h>
#include "sprintf.h"
#include "irc_net.h"
#include "dns.h"

/* Structure used to hold information about a dns child */
struct dnschild {
  pid_t pid;
  int pipe;
  
  struct ircproxy *proxy;
  void (*function)(struct ircproxy *, void *, struct in_addr *, const char *);
  void *data;

  struct dnschild *next;
};

/* Reply generated by a child */
struct dnsresult {
  int success;
  struct in_addr addr;
  char name[256];
};

/* forward declarations */
static struct dnsresult _dns_lookup(const char *, struct in_addr *);
static int _dns_startrequest(struct ircproxy *,
                             void (*)(struct ircproxy *, void *,
                                     struct in_addr *, const char *),
                             void *, struct in_addr *, const char *);

/* Children */
static struct dnschild *dnschildren = 0;

/* Function that looks up DNS request */
static struct dnsresult _dns_lookup(const char *name, struct in_addr *addr) {
  struct dnsresult res;
  struct hostent *info;
  pid_t pid;

  pid = getpid();

  memset(&res, 0, sizeof(struct dnsresult));
  if (name) {
    debug("%d: Looking up IP for '%s'", pid, name);
    info = gethostbyname(name);
  } else if (addr) {
    debug("%d: Lookup up name for '%s'", pid, inet_ntoa(*addr));
    info = gethostbyaddr((char *)addr, sizeof(struct in_addr), AF_INET);
  } else {
    info = 0;
  }

  if (info) {
    res.success = 1;

    res.addr.s_addr = *((unsigned long *) info->h_addr);
    if (info->h_name) {
      strncpy(res.name, info->h_name, 255);
      res.name[255] = 0;
    }

    debug("%d: Got '%s' (%s)", pid, res.name, inet_ntoa(res.addr));
  } else {
    debug("%d: No result", pid);
  }

  return res;
}

/* Function that starts a non-blocking DNS request. */
static int _dns_startrequest(struct ircproxy *proxy,
                             void (*function)(struct ircproxy *, void *,
                                              struct in_addr *, const char *),
                             void *data, struct in_addr *addr, const char *name)
{
  struct dnschild *child;
  int p[2];

  /* Pipe where the result will be placed on success */
  if (pipe(p)) {
    syscall_fail("pipe", 0, 0);
    function(proxy, data, 0, 0);
    return -1;
  }

  /* Allocate and place the child on the list now, to avoid race conditions */
  child = (struct dnschild *)malloc(sizeof(struct dnschild));
  child->pipe = p[0];
  child->proxy = proxy;
  child->function = function;
  child->data = data;
  child->next = dnschildren;
  dnschildren = child;

  /* Fork */
  child->pid = fork();
  if (child->pid == -1) {
    /* Error */
    syscall_fail("fork", 0, 0);
    dnschildren = child->next;
    close(p[1]);
    close(p[0]);
    free(child);
    function(proxy, data, 0, 0);
    return -1;
    
  } else if (child->pid) {
    /* Parent */
    debug("New DNS process started, pid %d", child->pid);
    close(p[1]);
    return 0;

  } else {
    struct dnsresult result;

    close(p[0]);
    
    /* Use ALARM to do timeouts */
    signal(SIGALRM, SIG_DFL);
    alarm(DNS_TIMEOUT);

    /* Do the lookup */
    result = _dns_lookup(name, addr);
    if (result.success) {
      /* Succeded, write to our parent and die */
      write(p[1], (void *)&result, sizeof(struct dnsresult));
      exit(0);
    } else {
      /* Didn't succeed */
      exit(1);
    }
  }
}

/* Called to end a DNS request.  0 = Not handled, >0 = Ok, <0 = Error */
int dns_endrequest(pid_t pid, int status) {
  struct dnschild *lastchild, *child;
  struct dnsresult result;
  struct in_addr *addr;
  char *name;
  size_t len;

  /* Check to see whether this was a DNS child */
  child = dnschildren;
  lastchild = 0;
  while (child) {
    if (child->pid == pid)
      break;

    lastchild = child;
    child = child->next;
  }
  if (!child)
    return 0;

  /* Remove it from the list */
  if (lastchild) {
    lastchild->next = child->next;
  } else {
    dnschildren = child->next;
  }

  debug("%d: Was a DNS child, getting result", pid);

  /* Parameters to call function with */
  name = 0;
  addr = 0;
  
  /* Read from pipe if child returned normally */
  if (!status) {
    len = read(child->pipe, (void *)&result, sizeof(struct dnsresult));
    if (len != sizeof(struct dnsresult)) {
      syscall_fail("read", 0, 0);
    } else if (result.success) {
      debug("%d: Got result", pid);

      addr = &(result.addr);
      if (!strlen(result.name)) {
        char *ip;

        /* No name received, so copy IP address into it */
        ip = inet_ntoa(result.addr);
        strncpy(result.name, ip, 255);
        result.name[255] = 0;

        debug("%d: Changed name to '%s'", pid, result.name);
      }
      name = result.name;
    }
  } else {
    debug("%d: DNS lookup returned %d", pid, status);
  }

  /* Call the function */
  child->function(child->proxy, child->data, addr, name);

  /* Clean up */
  close(child->pipe);
  free(child);

  return 1;
}

/* Kill off any children associated with an ircproxy */
int dns_delall(struct ircproxy *p) {
  struct dnschild *c, *l;
  int numdone;

  l = 0;
  c = dnschildren;
  numdone = 0;
  
  while (c) {
    if (c->proxy == p) {
      struct dnschild *n;

      n = c->next;
      debug("Killing DNS process %d", c->pid);
      kill(c->pid, SIGKILL);
      close(c->pipe);
      free(c);

      if (l) {
        c = l->next = n;
      } else {
        c = dnschildren = n;
      }
    } else {
      l = c;
      c = c->next;
    }
  }

  return numdone;
}

/* Kill off ALL dns children */
void dns_flush(void) {
  struct dnschild *c;

  c = dnschildren;
  while (c) {
    struct dnschild *n;

    n = c->next;
    debug("Killing DNS process %d", c->pid);
    kill(c->pid, SIGKILL);
    close(c->pipe);
    free(c);
    c = n;
  }

  dnschildren = 0;
}

/* Returns the IP address of a hostname */
int dns_addrfromhost(struct ircproxy *proxy, void *data, const char *name,
                     void (*function)(struct ircproxy *, void *,
                                      struct in_addr *, const char *)) {
  return _dns_startrequest(proxy, function, data, 0, name);
}

/* Returns the hostname of an IP address */
int dns_hostfromaddr(struct ircproxy *proxy, void *data, struct in_addr addr,
                     void (*function)(struct ircproxy *, void *,
                                      struct in_addr *, const char *)) {
  return _dns_startrequest(proxy, function, data, &addr, 0);
}

/* Fill a sockaddr_in from a hostname or hostname:port combo thing */
int dns_filladdr(struct ircproxy *proxy, const char *name,
                 const char *defaultport, int allowcolon,
                 struct sockaddr_in *result,
                 void (*function)(struct ircproxy *, void *,
                                  struct in_addr *, const char *),
                 void *data) {
  char *addr, *port;
  int ret = 0;

  memset(result, 0, sizeof(struct sockaddr_in));
  result->sin_family = AF_INET;
  if (defaultport)
    result->sin_port = dns_portfromserv(defaultport);

  addr = x_strdup(name);

  if (allowcolon) {
    port = strchr(addr, ':');

    if (port) {
      *(port++) = 0;

      if (strlen(port))
        result->sin_port = dns_portfromserv(port);
    }
  }

  ret = _dns_startrequest(proxy, function, data, 0, addr);

  free(addr);
  return ret;
}

/* Returns a network port number for a port as a string */
short dns_portfromserv(const char *serv) {
  struct servent *entry;

  entry = getservbyname(serv, "tcp");
  return (entry ? entry->s_port : htons(atoi(serv)));
}

/* Returns a service name for a network port number */
char *dns_servfromport(short port) {
  struct servent *entry;
  char *str;

  entry = getservbyport(port, "tcp");
  if (entry) {
    str = x_strdup(entry->s_name);
  } else {
    str = x_sprintf("%d", port);
  }

  return str;
}
